//Run the following Script on PINE EDITOR or any platform supporting Pine Script

// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © might-tree

//@version=5
strategy("Dead Cross Over", overlay=true, margin_long=100, margin_short=100)

FastIndicator = ta.ema(close, 10)
SlowIndicator = ta.ema(close, 100)

CrossUnder = (FastIndicator[0]-SlowIndicator[0] < 0 and FastIndicator[1]-SlowIndicator[1] > 0)
CrossOver = (FastIndicator[0]-SlowIndicator[0] > 0 and FastIndicator[1]-SlowIndicator[1] < 0)

plot(FastIndicator, color = color.rgb(87, 255, 92), linewidth = 1, title="Fast")
plot(SlowIndicator, color = #ff1269, title="Slow")
bgcolor(CrossUnder ? color.red : CrossOver ? color.green : na, title="Cross")


if (CrossOver) and SlowIndicator<close
    strategy.entry("Death Cross", strategy.long)

if (CrossUnder)
    strategy.close("Death Cross")
