//Run the following Script on PINE EDITOR or any platform supporting Pine Script

// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © might-tree

//@version=5
strategy("Swing Trade", overlay=true, margin_long=100, margin_short=100)

small_high = if(high[0]>high[1])
    high
small_low = if(low[0]<low[1])
    low

plot(high[0]>high[1]? small_high : small_low, color=#48b3ff, linewidth=2, title="Small Swing")


medium_high = if(high[0]>high[1] and high[1] > high[2])
    high
medium_low = if(low[0]<low[1] and low[1] < low[2])
    low

plot(high[0]>high[1]? medium_high : medium_low, color=color.rgb(241, 210, 98), linewidth=2, title="Medium Swing")


large_high = if(high[0]>high[1] and high[1] > high[2] and high[2] > high[3])
    high
large_low = if(low[0]<low[1] and low[1] < low[2] and low[2] < low[3])
    low

plot(high[0]>high[1]? large_high : large_low, color=color.rgb(250, 72, 226), linewidth=2, title="Large Swing")
