//Run the following Script on PINE EDITOR or any platform supporting Pine Script

// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © might-tree

//@version=5
strategy("My Custom Strategy 2", overlay=false, margin_long=100, margin_short=100)

my_vwma=ta.vwma(low,20)
my_hma=ta.hma(high,200)

highestHigh = ta.highest(close, 25)[1]
lowestLow   = ta.lowest(close, 25)[1]
randomPoint    = (highestHigh + lowestLow)/5

if high > highestHigh and close>my_vwma and close>my_hma
    strategy.entry("Enter Long", strategy.long)

if ta.crossunder(low, close)
    strategy.close("Enter Long", comment="Exit Long")

plot(my_vwma, color=color.green)
plot(my_hma, color=color.red)
plot(close, color=color.blue)
