// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © might-tree

//@version=5
strategy("My Custom Strategy 1", overlay=false, margin_long=100, margin_short=100)
import TradingView/ta/5

my_ema=ta.ema(low,20)
my_sma=ta.sma(low,20)
my_swma=ta.swma(close)

highestHigh = ta.highest(close, 25)[1]
lowestLow   = ta.lowest(close, 25)[1]
randomPoint    = (highestHigh + lowestLow)/5

if high > highestHigh and close>my_ema-5 and close>my_sma
    strategy.entry("Enter Long", strategy.long)

if ta.crossunder(low, close)
    strategy.close("Enter Long", comment="Exit Long")

plot(my_ema, color=color.green)
plot(my_sma, color=color.red)
plot(close, color=color.blue)
