//Run the following Script on PINE EDITOR or any platform supporting Pine Script

// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © might-tree

//@version=5
indicator("Intraday Gap Detector", overlay=true)
size = 0.2
days = 30

gap_width = math.round(((((open - close[1]) / close[1])*100)*100)/100)

var x = close

if math.abs(gap_width) > size and (timenow - time) < 1000*60*60*24*days
    x := close[1]
    
    if gap_width < 0
        line.new(bar_index-1, x, bar_index, x, extend=extend.right, style= line.style_arrow_left, color=color.rgb(27, 146, 63), width=1)
        label.new(timenow, x, xloc= xloc.bar_time, text="Gap Up", color=color.rgb(27, 146, 63), textcolor=color.white)
    else
        line.new(bar_index-1, x, bar_index, x, extend=extend.right, style= line.style_arrow_left, color=color.rgb(171,8,8), width=1)
        label.new(timenow, x, xloc= xloc.bar_time, text="Gap Down", color=color.rgb(171, 8, 8), textcolor=color.white)
